// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAEMma179qtJ3JrDQxnNl5pwd7wnr3fk',
    appId: '1:495368636469:android:e60f6a6559715b71df497c',
    messagingSenderId: '495368636469',
    projectId: 'social-media-app-d516f',
    storageBucket: 'social-media-app-d516f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaFuc7mxZERJJNdhBJc6h5r-0IMeQfEI',
    appId: '1:495368636469:ios:e68bea3370fe43bddf497c',
    messagingSenderId: '495368636469',
    projectId: 'social-media-app-d516f',
    storageBucket: 'social-media-app-d516f.firebasestorage.app',
    androidClientId: '495368636469-v49jgp84n5lnvpl49gm9b2au5sje59i9.apps.googleusercontent.com',
    iosClientId: '495368636469-et6gef11tsks209opi850esqfq4v1kan.apps.googleusercontent.com',
    iosBundleId: 'com.example.practics',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6mKu8Vkj4hCrvUF9Pml-PQSeYfUudDc',
    appId: '1:495368636469:web:68e1241b40830352df497c',
    messagingSenderId: '495368636469',
    projectId: 'social-media-app-d516f',
    authDomain: 'social-media-app-d516f.firebaseapp.com',
    storageBucket: 'social-media-app-d516f.firebasestorage.app',
    measurementId: 'G-FTBMGBXN75',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlaFuc7mxZERJJNdhBJc6h5r-0IMeQfEI',
    appId: '1:495368636469:ios:e68bea3370fe43bddf497c',
    messagingSenderId: '495368636469',
    projectId: 'social-media-app-d516f',
    storageBucket: 'social-media-app-d516f.firebasestorage.app',
    androidClientId: '495368636469-v49jgp84n5lnvpl49gm9b2au5sje59i9.apps.googleusercontent.com',
    iosClientId: '495368636469-et6gef11tsks209opi850esqfq4v1kan.apps.googleusercontent.com',
    iosBundleId: 'com.example.practics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD6mKu8Vkj4hCrvUF9Pml-PQSeYfUudDc',
    appId: '1:495368636469:web:131fdc5677bc80e8df497c',
    messagingSenderId: '495368636469',
    projectId: 'social-media-app-d516f',
    authDomain: 'social-media-app-d516f.firebaseapp.com',
    storageBucket: 'social-media-app-d516f.firebasestorage.app',
    measurementId: 'G-QLYK4LH03Q',
  );

}